[workspace]
authors = ["maxreith <maxpr@gmx.com>"]
channels = ["conda-forge"]
name = "maxreith.github.io"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
serve = "bundle exec jekyll serve"

[dependencies]
ruby = ">=3.4.8,<4"
c-compiler = ">=1.11.0,<2"
cxx-compiler = ">=1.11.0,<2"
